Repository automationbroker/bundle-lib, pull requests merged in 2018-05, with the labels that each got.

#77 Bug 1576881 - Add discovery to openshift adapter
  registries/adapters/partner_rhcc_adapter.go
  registries/adapters/partner_rhcc_adapter_test.go
  registries/registry.go
Labels: 0.1.x

#65 removing the bundle execution to runtime.
  bundle/bind.go
  bundle/deprovision.go
  bundle/executor.go
  bundle/provision_or_update.go
  bundle/types.go
  bundle/unbind.go
  runtime/run_bundle.go
  runtime/run_bundle_test.go
  runtime/runtime.go
  runtime/runtime_test.go
  runtime/state.go
Labels: 0.2.x, enhancement, needs-review

#69 Allow Bundle to run in a target namespace
  runtime/runtime.go
Labels: 0.2.x, needs-review

#86 Update openshift adapter and tests for http
  registries/adapters/openshift_adapter.go
  registries/adapters/openshift_adapter_test.go
Labels: bug

#74 Bug 1576881 - Add /v2/_catalog support for openshift adapter
  registries/adapters/partner_rhcc_adapter.go
  registries/adapters/partner_rhcc_adapter_test.go
  registries/registry.go
Labels: 0.2.x
